// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qM1iqgiTPNkjXLbe9OIzKghBhJzuIr4',
    appId: '1:358149224953:web:d1b12a67be80927956a528',
    messagingSenderId: '358149224953',
    projectId: 'plogging-32dfa',
    authDomain: 'plogging-32dfa.firebaseapp.com',
    storageBucket: 'plogging-32dfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYB5F748PI3CiGklgm81Jntm-oH0EJK0',
    appId: '1:358149224953:android:1f02901a3601e09056a528',
    messagingSenderId: '358149224953',
    projectId: 'plogging-32dfa',
    storageBucket: 'plogging-32dfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBdFsOQazrTlfMjUkur5YVl_fpNxvjS4U',
    appId: '1:358149224953:ios:d605222e5e4cba7056a528',
    messagingSenderId: '358149224953',
    projectId: 'plogging-32dfa',
    storageBucket: 'plogging-32dfa.appspot.com',
    iosBundleId: 'com.example.everyplogging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBdFsOQazrTlfMjUkur5YVl_fpNxvjS4U',
    appId: '1:358149224953:ios:d605222e5e4cba7056a528',
    messagingSenderId: '358149224953',
    projectId: 'plogging-32dfa',
    storageBucket: 'plogging-32dfa.appspot.com',
    iosBundleId: 'com.example.everyplogging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0qM1iqgiTPNkjXLbe9OIzKghBhJzuIr4',
    appId: '1:358149224953:web:3a1ecf4cd6c9fc9a56a528',
    messagingSenderId: '358149224953',
    projectId: 'plogging-32dfa',
    authDomain: 'plogging-32dfa.firebaseapp.com',
    storageBucket: 'plogging-32dfa.appspot.com',
  );
}
